# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Lint Dockerfiles

on:
  push:
    branches: 
      - '**'
      
jobs:
  dockerfile_linting:
    name: Dockerfile linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Alpine Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./docker/alpine/Dockerfile.build
          config: ./docker/.config/hadolint.yml
      - name: Lint Debian Bookworm Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./docker/debian-bookworm/Dockerfile.build
          config: ./docker/.config/hadolint.yml
      - name: Lint Debian Bullseye Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./docker/debian-bullseye/Dockerfile.build
          config: ./docker/.config/hadolint.yml
      - name: Lint Debian Bullseye Self-contained Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./docker/debian-bullseye/selfcontained/Dockerfile
          config: ./docker/.config/hadolint.yml